@domain = http://localhost:3000
@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDYxOTE4NDd9.JpvL9XPT8jiEgErUpzpPH9sv7v81IPtNX5hnu-cxaKY
### Users create (signup)
POST {{ domain }}/users 
Content-Type: application/json

{
  "email": "helloherokim@gmail.com",
  "username": "Ro",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (logged in)
POST {{ domain }}/sessions
Content-Type: application/json

{
  "email": "helloherokim@gmail.com",
  "password": "password"
}

### Users show
GET {{ domain }}/users/1
Content-Type: application/json
Authorization: Bearer {{ jwt }}